"""Add intelligence layer fields

Revision ID: 5b557a428cbb
Revises: 73606bff53ff
Create Date: 2025-12-24 15:37:46.361814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b557a428cbb'
down_revision: Union[str, Sequence[str], None] = '73606bff53ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use inspector to check if columns already exist
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    existing_columns = [c['name'] for c in inspect_obj.get_columns('articles')]
    
    if 'read_time_minutes' not in existing_columns:
        op.add_column('articles', sa.Column('read_time_minutes', sa.Integer(), nullable=True))
    
    if 'sentiment' not in existing_columns:
        op.add_column('articles', sa.Column('sentiment', sa.String(length=20), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'sentiment')
    op.drop_column('articles', 'read_time_minutes')
    # ### end Alembic commands ###
