"""remove_sentiment_column

Revision ID: a030ea163f4d
Revises: 9e31481c2244
Create Date: 2025-12-26 22:40:16.050061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a030ea163f4d'
down_revision: Union[str, Sequence[str], None] = '9e31481c2244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspect_obj = sa.inspect(conn)
    existing_columns = [c['name'] for c in inspect_obj.get_columns('articles')]
    
    if 'sentiment' in existing_columns:
        op.drop_column('articles', 'sentiment')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('sentiment', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
